services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    working_dir: /app
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle:cached
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    environment:
      - BINDING=0.0.0.0
      - EDITOR=vim

volumes:
  bundle:
